# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFusionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=255)),
            ],
        ),
    ]
