# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_locations', '0002_googlefusiontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemaplocation',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
